#!/bin/sh
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "Usage: mpv [-q] [MPLAYER OPTIONS]... FILE"
	echo "Play a video in fullscreen in the current console using MPlayer"
	echo "-q		suppress status messages; similar to passing -really-quiet to MPlayer"
	echo "-h, --help	show this help message"
	exit
fi
if [ "$1" == "-q" ]; then
	quiet=-really-quiet
	shift
fi

fb_height=`cat /sys/class/graphics/fb0/virtual_size | cut -f2 -d,`
vid_height=`mplayer -really-quiet -vo null -ao null -identify -frames 0 "$@" 2>/dev/null | grep ID_VIDEO_HEIGHT | cut -f2 -d=`
vid_width=`mplayer -really-quiet -vo null -ao null -identify -frames 0 "$@" 2>/dev/null | grep ID_VIDEO_WIDTH | cut -f2 -d=`
height_factor=`echo "$fb_height/$vid_height" | bc -l`
optimal_width=`echo "$height_factor*$vid_width" | bc`

mplayer $quiet -vo fbdev2 -zoom -fs -xy $optimal_width "$@"
