#!/bin/sh
if [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ $# -eq 0 ]; then
	echo "Usage: mpv [-q] [MPLAYER OPTIONS]... FILE"
	echo "Play a video in fullscreen in the current console using MPlayer"
	echo "-q		suppress status messages; similar to passing -really-quiet to MPlayer"
	echo "-h, --help	show this help message"
	exit
fi
if [ "$1" == "-q" ]; then
	quiet=-really-quiet
	shift
fi

fb_height=`cat /sys/class/graphics/fb0/virtual_size | cut -f2 -d,`
fb_width=`cat /sys/class/graphics/fb0/virtual_size | cut -f1 -d,`
vid_height=`mplayer -really-quiet -vo null -ao null -identify -frames 0 "$@" 2>/dev/null | grep ID_VIDEO_HEIGHT | cut -f2 -d=`
vid_width=`mplayer -really-quiet -vo null -ao null -identify -frames 0 "$@" 2>/dev/null | grep ID_VIDEO_WIDTH | cut -f2 -d=`
height_factor=`echo "$fb_height/$vid_height" | bc -l`
optimal_width=`echo "$height_factor*$vid_width" | bc -l | cut -f1 -d.`

if [ -z "$optimal_width" ]; then
	echo "Video is missing metadata, playing may fail." >&2
	optimal_width=$fb_width
elif [ $optimal_width -gt $fb_width ]; then
	optimal_width=$fb_width
fi

mplayer $quiet -vo fbdev2 -zoom -fs -framedrop -xy $optimal_width "$@"
